### ISSUE TITLE
7.0: Add Charity (aka growth) Notification

### ISSUE THREAD

**Issue by cancelself** [nrsh-society/zendo#23]
1: Growth / Donate Notification : 5k with the community to givedirectly. 
2: Loading Screen: We are doing away 5k to GD - you have to mediate to help us give us -
3: Meditation Trainer: with whatever changes.
4: Results Screen: looks like activity or the watch results?
5: Sharing?

**Comment by dpurdy** [comment]
@ghostfacex  is going to think about this from a watch first standpoint?

**Comment by dpurdy** [comment]
<img width="228" alt="image" src="https://user-images.githubusercontent.com/332509/86546362-5b801700-bee9-11ea-9563-85005387b165.png">

@ghostfacex : I took a stab at it.
